sync changes from new-core22 branch

diff --git a/scripts/desktop-launch b/scripts/desktop-launch
--- a/scripts/desktop-launch
+++ b/scripts/desktop-launch
@@ -6,6 +6,13 @@
 # shellcheck disable=SC2034
 START=$(date +%s.%N)
 
+if ! snapctl is-connected "gaming-mesa"; then
+  echo "ERROR: not connected to the gaming-mesa content interface."
+  echo "To connect:"
+  echo "sudo snap connect steam:gaming-mesa gaming-graphics-core22"
+  exit 1
+fi
+
 # ensure_dir_exists calls `mkdir -p` if the given path is not a directory.
 # This speeds up execution time by avoiding unnecessary calls to mkdir.
 #
@@ -39,7 +46,7 @@ fi
 REALHOME=$(getent passwd $UID | cut -d ':' -f 6)
 
 export SNAP_DESKTOP_RUNTIME=$SNAP
-export WINE_DESKOP_RUNTIME=$SNAP/wine-runtime
+export WINE_DESKTOP_RUNTIME=$SNAP/wine-runtime
 
 # Set config folder to local path
 export XDG_CONFIG_HOME="$SNAP_USER_COMMON/.config"
@@ -65,21 +72,13 @@ if [[ -d $SNAP_USER_DATA/.config ]]; then
   rm -r $SNAP_USER_DATA/.config
 fi
 
-if [ "$SNAP_ARCH" = "amd64" ]; then
-  ARCH="x86_64-linux-gnu"
-elif [ "$SNAP_ARCH" = "armhf" ]; then
-  ARCH="arm-linux-gnueabihf"
-elif [ "$SNAP_ARCH" = "arm64" ]; then
-  ARCH="aarch64-linux-gnu"
-elif [ "$SNAP_ARCH" = "ppc64el" ]; then
-  ARCH="powerpc64le-linux-gnu"
+# We need to force our snap's arch to i386, but this only works on an i386 compatible arch
+if [ "$SNAP_ARCH" = "amd64" ] || [ "$SNAP_ARCH" = "i386" ]; then
+  export SNAP_LAUNCHER_ARCH_TRIPLET="i386-linux-gnu"
 else
-  ARCH="$SNAP_ARCH-linux-gnu"
+  echo "UNSUPPORTED ARCH $SNAP_ARCH - only i386 and x86_64 are supported"
+  exit 1
 fi
-
-# Force i386
-export ARCH="i386-linux-gnu"
-export SNAP_LAUNCHER_ARCH_TRIPLET="$ARCH"
 
 ###############################################
 # Launcher common exports for any desktop app #
@@ -143,45 +142,62 @@ function is_subpath() {
 }
 
 append_dir PATH "$SNAP_DESKTOP_RUNTIME/usr/bin"
-append_dir PATH "$WINE_DESKOP_RUNTIME/usr/bin"
+append_dir PATH "$WINE_DESKTOP_RUNTIME/usr/bin"
 
 # XKB config
-export XKB_CONFIG_ROOT="$WINE_DESKOP_RUNTIME/usr/share/X11/xkb"
+export XKB_CONFIG_ROOT="$WINE_DESKTOP_RUNTIME/usr/share/X11/xkb"
 
 # Give XOpenIM a chance to locate locale data.
 # This is required for text input to work in SDL2 games.
-export XLOCALEDIR="$WINE_DESKOP_RUNTIME/usr/share/X11/locale"
+export XLOCALEDIR="$WINE_DESKTOP_RUNTIME/usr/share/X11/locale"
 
 # Set XCursors path
-export XCURSOR_PATH="$WINE_DESKOP_RUNTIME/usr/share/icons"
+export XCURSOR_PATH="$WINE_DESKTOP_RUNTIME/usr/share/icons"
 prepend_dir XCURSOR_PATH "$SNAP/share/icons"
 
-# Mesa Libs for OpenGL support
-append_dir LD_LIBRARY_PATH "$WINE_DESKOP_RUNTIME/usr/\$LIB/mesa"
-append_dir LD_LIBRARY_PATH "$WINE_DESKOP_RUNTIME/usr/\$LIB/mesa-egl"
-# append_dir LD_LIBRARY_PATH "$SNAP_DESKTOP_RUNTIME/graphics/usr/\$LIB/mesa"
-# append_dir LD_LIBRARY_PATH "$SNAP_DESKTOP_RUNTIME/graphics/usr/\$LIB/mesa-egl"
+### Fonts
 
-append_dir LD_LIBRARY_PATH "$SNAP_DESKTOP_RUNTIME/graphics/usr/\$LIB"
+export FONTCONFIG_PATH="$WINE_DESKTOP_RUNTIME/etc/fonts"
+
+#### Setting up graphics content snap paths
+
+GRAPHICS_CORE_LIB="$SNAP_DESKTOP_RUNTIME/graphics/usr/lib"
+GRAPHICS_CORE_SHARE="$SNAP_DESKTOP_RUNTIME/graphics/usr/share"
+
+# Mesa Libs for OpenGL support
+append_dir LD_LIBRARY_PATH "$GRAPHICS_CORE_LIB/i386-linux-gnu/mesa"
+append_dir LD_LIBRARY_PATH "$GRAPHICS_CORE_LIB/i386-linux-gnu/mesa-egl"
+append_dir LD_LIBRARY_PATH "$GRAPHICS_CORE_LIB/x86_64-linux-gnu/mesa"
+append_dir LD_LIBRARY_PATH "$GRAPHICS_CORE_LIB/x86_64-linux-gnu/mesa-egl"
+append_dir LD_LIBRARY_PATH "$GRAPHICS_CORE_LIB/i386-linux-gnu"
+append_dir LD_LIBRARY_PATH "$GRAPHICS_CORE_LIB/x86_64-linux-gnu"
+
+# Ensure nvidia driver libs are loaded
+prepend_dir LD_LIBRARY_PATH "/var/lib/snapd/lib/gl/"
 
 # Tell libGL and libva where to find the drivers
-export LIBGL_DRIVERS_PATH="$WINE_DESKOP_RUNTIME/usr/\$LIB/dri"
-append_dir LIBGL_DRIVERS_PATH "$SNAP_DESKTOP_RUNTIME/graphics/usr/\$LIB/dri"
-append_dir LD_LIBRARY_PATH "$LIBGL_DRIVERS_PATH"
+export LIBGL_DRIVERS_PATH="$GRAPHICS_CORE_LIB/i386-linux-gnu/dri"
+append_dir LIBGL_DRIVERS_PATH "$GRAPHICS_CORE_LIB/x86_64-linux-gnu/dri"
 
-append_dir LIBVA_DRIVERS_PATH "$WINE_DESKOP_RUNTIME/usr/\$LIB/dri"
-append_dir LIBVA_DRIVERS_PATH "$SNAP_DESKTOP_RUNTIME/graphics/usr/\$LIB/dri"
+# EGL vendor files on glvnd enabled systems
+prepend_dir __EGL_VENDOR_LIBRARY_DIRS "/var/lib/snapd/lib/glvnd/egl_vendor.d"
+append_dir __EGL_VENDOR_LIBRARY_DIRS "$GRAPHICS_CORE_SHARE/glvnd/egl_vendor.d"
 
-# Set where the VDPAU drivers are located
-export VDPAU_DRIVER_PATH="/usr/\$LIB/vdpau/"
-if [ -e "/var/lib/snapd/lib/gl/vdpau/libvdpau_nvidia.so" ]; then
-  export VDPAU_DRIVER_PATH="/var/lib/snapd/lib/gl/vdpau"
-  # Prevent picking VA-API (Intel/AMD) over NVIDIA VDPAU; on PRIME systems for example
-  unset LIBVA_DRIVERS_PATH
-fi
+append_dir LIBVA_DRIVERS_PATH "$GRAPHICS_CORE_LIB/i386-linux-gnu/dri"
+append_dir LIBVA_DRIVERS_PATH "$GRAPHICS_CORE_LIB/x86_64-linux-gnu/dri"
+
+### Fix for Vulkan ICD paths being hardcoded under root
+
+VULKAN_OVERRIDES=$SNAP_USER_COMMON/.vulkan/icd.d
+mkdir -p $VULKAN_OVERRIDES
+
+ICDs=$GRAPHICS_CORE_SHARE/vulkan/icd.d/; 
+for f in $(ls $ICDs); do 
+  cat "$ICDs/$f" | jq '.ICD.library_path=$prefix+.ICD.library_path' --arg prefix "$SNAP/graphics" > "$VULKAN_OVERRIDES/$f"
+done
 
 # Export Vulkan ICD filename paths
-export VK_ICD_FILENAMES="/var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json:$WINE_DESKOP_RUNTIME/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:$WINE_DESKOP_RUNTIME/usr/share/vulkan/icd.d/intel_icd.x86_64.json"
+export VK_ICD_FILENAMES="/var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json:$VULKAN_OVERRIDES/radeon_icd.x86_64.json:$VULKAN_OVERRIDES/radeon_icd.i686.json:$VULKAN_OVERRIDES/intel_icd.x86_64.json:$VULKAN_OVERRIDES/intel_icd.i686.json"
 
 # Workaround in snapd for proprietary nVidia drivers mounts the drivers in
 # /var/lib/snapd/lib/gl that needs to be in LD_LIBRARY_PATH
@@ -190,31 +206,33 @@ export VK_ICD_FILENAMES="/var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json:$WINE_D
 append_dir LD_LIBRARY_PATH "/var/lib/snapd/lib/gl"
 append_dir LD_LIBRARY_PATH "/var/lib/snapd/lib/gl/vdpau"
 
+
+### Audio stuff
+
+append_dir LD_LIBRARY_PATH "$WINE_DESKTOP_RUNTIME/usr/lib/x86_64-linux-gnu/alsa-lib"
+append_dir LD_LIBRARY_PATH "$WINE_DESKTOP_RUNTIME/usr/share/alsa"
+
 # Unity7 export (workaround for https://launchpad.net/bugs/1638405)
-append_dir LD_LIBRARY_PATH "$WINE_DESKOP_RUNTIME/usr/\$LIB/libunity"
+append_dir LD_LIBRARY_PATH "$WINE_DESKTOP_RUNTIME/usr/lib/i386-linux-gnu/libunity"
 
 # Pulseaudio export
-append_dir LD_LIBRARY_PATH "$WINE_DESKOP_RUNTIME/usr/\$LIB/pulseaudio"
+append_dir LD_LIBRARY_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/i386-linux-gnu/pulseaudio"
 
 # SAMBA Libs for ntlm_auth to function
-append_dir LD_LIBRARY_PATH "$WINE_DESKOP_RUNTIME/usr/\$LIB/samba"
-
-# EGL vendor files on glvnd enabled systems
-prepend_dir __EGL_VENDOR_LIBRARY_DIRS "/var/lib/snapd/lib/glvnd/egl_vendor.d"
-append_dir __EGL_VENDOR_LIBRARY_DIRS "$WINE_DESKOP_RUNTIME/usr/share/glvnd/egl_vendor.d"
+append_dir LD_LIBRARY_PATH "$WINE_DESKTOP_RUNTIME/usr/lib/i386-linux-gnu/samba"
 
 # Tell GStreamer where to find its plugins
-export GST_PLUGIN_PATH="$WINE_DESKOP_RUNTIME/usr/\$LIB/gstreamer-1.0"
-export GST_PLUGIN_SYSTEM_PATH="$WINE_DESKOP_RUNTIME/usr/\$LIB/gstreamer-1.0"
+export GST_PLUGIN_PATH="$WINE_DESKTOP_RUNTIME/usr/lib/i386-linux-gnu/gstreamer-1.0"
+export GST_PLUGIN_SYSTEM_PATH="$WINE_DESKTOP_RUNTIME/usr/lib/i386-linux-gnu/gstreamer-1.0"
 # gst plugin scanner doesn't install in the correct path: https://github.com/ubuntu/snapcraft-desktop-helpers/issues/43
-export GST_PLUGIN_SCANNER="$WINE_DESKOP_RUNTIME/usr/\$LIB/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner"
+export GST_PLUGIN_SCANNER="$WINE_DESKTOP_RUNTIME/usr/lib/i386-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner"
 
 # XDG Config
-prepend_dir XDG_CONFIG_DIRS "$WINE_DESKOP_RUNTIME/etc/xdg"
+prepend_dir XDG_CONFIG_DIRS "$WINE_DESKTOP_RUNTIME/etc/xdg"
 prepend_dir XDG_CONFIG_DIRS "$SNAP/etc/xdg"
 
 # Define snaps' own data dir
-prepend_dir XDG_DATA_DIRS "$WINE_DESKOP_RUNTIME/usr/share"
+prepend_dir XDG_DATA_DIRS "$WINE_DESKTOP_RUNTIME/usr/share"
 prepend_dir XDG_DATA_DIRS "$SNAP/usr/share"
 prepend_dir XDG_DATA_DIRS "$SNAP/share"
 prepend_dir XDG_DATA_DIRS "$SNAP/data-dir"
@@ -242,7 +260,7 @@ ensure_dir_exists "$XDG_CACHE_HOME"
 ensure_dir_exists "$XDG_RUNTIME_DIR" -m 700
 
 # Ensure the app finds locale definitions (requires locales-all to be installed)
-append_dir LOCPATH "$WINE_DESKOP_RUNTIME/usr/lib/locale"
+append_dir LOCPATH "$WINE_DESKTOP_RUNTIME/usr/lib/locale"
 
 # If detect wayland server socket, then set environment so applications prefer
 # wayland, and setup compat symlink (until we use user mounts. Remember,
@@ -298,7 +316,7 @@ if [ "$wayland_available" = true ]; then
   # Does not hurt to specify this as well, just in case
   export QT_QPA_PLATFORM=wayland-egl
 fi
-append_dir GTK_PATH "$WINE_DESKOP_RUNTIME/usr/\$LIB/gtk-3.0"
+append_dir GTK_PATH "$WINE_DESKTOP_RUNTIME/usr/lib/i386-linux-gnu/gtk-3.0"
 
 ###############################
 # Mark update and exec binary #
